# Generated by Django 3.2 on 2022-06-26 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drugstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drugstore',
            options={'verbose_name': 'Drugstore', 'verbose_name_plural': 'Drugstores'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.AlterModelOptions(
            name='medicineregister',
            options={'verbose_name': 'Register medicine', 'verbose_name_plural': 'Register medicines'},
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='address',
            field=models.TextField(blank=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='drugstore',
            name='users',
            field=models.ManyToManyField(null=True, related_name='drugstores', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='drugstore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='drugstore.drugstore', verbose_name='Drugstore'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugstore.medicineregister', verbose_name='Medicine register'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='medicineregister',
            name='category',
            field=models.CharField(blank=True, max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='medicineregister',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='medicineregister',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='medicineregister',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
