# Generated by Django 3.2 on 2022-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0002_auto_20220626_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineregister',
            name='category',
            field=models.CharField(blank=True, choices=[('Aerossol', 'Aerossol'), ('Ampola', 'Ampola'), ('Comprimido', 'Comprimido'), ('Creme', 'Creme'), ('Gel', 'Gel'), ('Gotas', 'Gotas'), ('Injetável', 'Injetável'), ('Loção', 'Loção'), ('Pomada', 'Pomada'), ('Suspensão', 'Suspensão'), ('Xarope', 'Xarope')], default='Comprimido', max_length=50),
        ),
    ]
