# Generated by Django 3.2 on 2022-07-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0003_alter_medicineregister_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineregister',
            name='id_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='ID name'),
        ),
    ]
