# Generated by Django 4.0.6 on 2022-07-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugstore', '0004_medicineregister_id_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugstore',
            name='phone',
            field=models.CharField(default='(12) 123456789', max_length=20, verbose_name='Phone'),
        ),
    ]
